server:
  #项目端口
  port: 8081
  servlet:
    #    项目路径
    context-path: /boot


picPath: d:/xxx/yyy

aliyun:
  x: xx
  y: yy
  z: zz

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

#  thymeleaf:
#    prefix: classpath:/templates/ # 访问template下的html文件需要配置模板，映射，路径指向
#    suffix: .html
#    cache: false # 开发时关闭缓存,不然没法看到实时页面







